version: "3.8"
services:
  postgres:
    image: postgres:alpine
    container_name: surfpsot-db
    environment:
      POSTGRES_DB: 1surf2spot3
      POSTGRES_USER: surfpostgresspot
      POSTGRES_PASSWORD: 1surf2spot3
      ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
